services:
  # Worker Proces
  vgg_histo_worker:
    container_name: vgg_histo_worker
    image: ikem-worker
    volumes:
      - /opt/histo-backend/iedl_root_dir:/iedl_root_dir
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      REDIS_HOST: vgg_histo_redis
      REDIS_PORT: 6379
      IEDL_ROOT_DIR: /iedl_root_dir
    networks:
      - vgg_histo_network


networks:
  vgg_histo_network:
    driver: bridge

volumes:
  db_data:
    external: true